---
# tasks file for mrhoads.containerd

- name: Copy containerd.conf
  copy:
    src: containerd.conf
    dest: /etc/modules-load.d/containerd.conf
  become: true

- name: enable necessary kernel modules
  modprobe:
    name: overlay
    state: present
  become: true

- name: enable br_netfilter module
  modprobe:
    name: br_netfilter
    state: present
  become: true

- name: reload kernel modules
  command: modprobe overlay && modprobe br_netfilter
  become: true

- name: Add docker apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present

- name: add docker apt
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }}  stable
    state: present
  become: yes

- name: install containerd.io
  apt:
    name: containerd.io
  become: true

- name: configure containerd
  file:
    path: /etc/containerd
    state: directory
  become: true

- name: create default config for containerd
  command: containerd config default > /etc/containerd/config.toml
  become: true

- name: restart containerd service
  systemd:
    name: containerd
    daemon_reload: yes
    state: restarted